import{a as y,S as L,i as l}from"./assets/vendor-hwdYKDic.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const b="48848365-f4e25352a2e58b0aa69d4606d",v="https://pixabay.com/api/",q=40;async function S(o,t){const s=`${v}?key=${b}&q=${encodeURIComponent(o)}&image_type=photo&per_page=${q}&page=${t}`;try{return(await y.get(s)).data}catch(i){throw console.error("Error fetching images:",i),i}}let d;function $(o,t=!1){const s=document.querySelector(".gallery");t&&(s.innerHTML="");const i=o.map(({previewURL:e,largeImageURL:r,tags:n})=>`<li class="gallery-item">
          <a class="gallery-link" href="${r}">
            <img class="gallery-image"
                 src="${e}"
                 data-source="${r}"
                 alt="${n}" />
          </a>
        </li>`).join("");s.insertAdjacentHTML("beforeend",i),d?d.refresh():d=new L(".gallery a",{captionsData:"alt",captionDelay:250})}const g=document.querySelector(".search-form"),w=g.querySelector("input[name='text']"),a=document.querySelector(".load-more"),u=document.querySelector(".end-notification"),h=document.getElementById("loader");let c=1,f="",m=0;async function p(o,t){try{h.classList.remove("hidden-loader");const s=await S(o,t);if(m=s.totalHits,$(s.hits,t===1),s.hits.length===0){l.error({title:"Error",message:"No images found. Try another search!",position:"topRight"}),a.classList.add("hidden");return}t*40<m?(a.classList.remove("hidden"),u.classList.add("hidden")):(a.classList.add("hidden"),u.classList.remove("hidden"),l.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),I()}catch{l.error({title:"Error",message:"Failed to fetch images. Please try again!",position:"topRight"})}finally{h.classList.add("hidden-loader")}}function I(){const o=document.querySelectorAll(".gallery-item");if(o.length>0){const{height:t}=o[0].getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}g.addEventListener("submit",o=>{o.preventDefault();const t=w.value.trim();if(t===""){l.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}f=t,c=1,m=0,a.classList.add("hidden"),u.classList.add("hidden"),p(f,c)});a.addEventListener("click",()=>{c+=1,p(f,c)});
//# sourceMappingURL=index.js.map
